# -*- Makefile -*-
### Makefile - VHDL Makefile generated by Emacs VHDL Mode 3.38.1

# Directory : "~/server/school/jaar4/digitale_techniek/wekker/digitech_wekker/"
# Platform  : GHDL
# Generated : 2020-09-25 11:35:00 harm


# Define compilation command and options

COMPILE = ghdl
OPTIONS = -i --workdir=work --ieee=synopsys -fexplicit 


# Define library paths

LIBRARY-work = work


# Define library unit files

UNIT-work-alarmclock = \
	$(LIBRARY-work)/alarmclock/entity
UNIT-work-alarmclock-wekker_arch = \
	$(LIBRARY-work)/alarmclock/wekker_arch


# Define list of all library unit files

ALL_UNITS = \
	$(UNIT-work-alarmclock) \
	$(UNIT-work-alarmclock-wekker_arch)



# Rule for compiling entire design

all : \
		library \
		$(ALL_UNITS)


# Rule for cleaning entire design

clean : 
	-rm -f $(ALL_UNITS)


# Rule for creating library directory

library : \
		$(LIBRARY-work)

$(LIBRARY-work) :
	mkdir $(LIBRARY-work)


.PHONY : all clean library


# Rules for compiling single library units and their subhierarchy

alarmclock \
ALARMCLOCK : \
		library \
		$(UNIT-work-alarmclock) \
		$(UNIT-work-alarmclock-wekker_arch)


# Rules for compiling single library unit files

$(UNIT-work-alarmclock) : \
		ALARMCLOCK.vhd
	$(COMPILE) $(OPTIONS) ALARMCLOCK.vhd

$(UNIT-work-alarmclock-wekker_arch) : \
		ALARMCLOCK_wekker_arch.vhd \
		$(UNIT-work-alarmclock)
	$(COMPILE) $(OPTIONS) ALARMCLOCK_wekker_arch.vhd


### Makefile ends here
