3
MSGERROR
118
An index constraint is applied to type INTEGER, which is not an unconstrained array (or access to unconstrained array)
NROOT 17 2 
!#@VHDL VENTUNIT 0 ALARMCLOCK $ wekker 
!#@VHDL VARCHOBJECT 0 wekker_arch $ wekker 
MSGERROR
118
An index constraint is applied to type INTEGER, which is not an unconstrained array (or access to unconstrained array)
NROOT 18 2 
!#@VHDL VENTUNIT 0 ALARMCLOCK $ wekker 
!#@VHDL VARCHOBJECT 0 wekker_arch $ wekker 
MSGNONE
45
Compilation of ALARMCLOCK(wekker_arch) failed
NROOT -1 0 
